== Platform Requirements

To support the Pathways activities a platform with the following features and attributes was required:

-	Supports open and collaborative development of science outputs
-	Centralizes access to the science outputs
-	Provides tools and applications to engage the public and support decision making

[.right]
.R5 Principles
****
- Re-runnable (R1)
- Repeatable (R2)
- Reproducible (R3)
- Reusable (R4)
- Replicable (R5)
****

[.left]
The generation of science outputs is becoming increasingly reliant on software code to automate processing, quality control, and publishing. Considerable attention was paid to alignment with best practices for Open Science (i.e., FAIR Principles) and scientific software code (i.e., R5 Principles).

[.right]
.FAIR Principles
****
- Findable
- Accessible
- Interoperable
- Reusable
****

The scale and scope of the data involved in the project necessitated an approach that not only streamlined the production of science-based outputs, but also provided for a high degree of collaboration across many disciplines (e.g., policy, technology, and science) and stakeholders (e.g., provincial, municipal).

Decision support requirements were well understood at the outset. A comprehensive set of requirements for a multitude of stakeholders was developed footnote:[https://opendrr.github.io/documentation/docs/opendrr-platform.html]. The diversity of the stakeholders and their specific needs necessitated a multi-channel approach since a single application was deemed to be insufficient to serve all use cases effectively.

With development led out of the Government of Canada the platform had to comply with requirements for publishing science outputs including standardized metadata, open data, support for both official languages, accessibility, and compliance with scientific integrity and publication policies. The scientific integrity and publishing requirements were particularly problematic as they traditionally pushed the development of the science behind closed doors. To comply with policy while supporting the objectives of the project, a balanced approach that prioritizes openness and transparency is needed.
